### ISSUE TITLE
Module: graphics and figures

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/handsonscicomp#4]
Should there be a module about how to make figures?  I can see two sides, technical (e.g. matplotlib), and philosophical (size, layout, colors, etc).

Not exactly about computing but related, and usually not taught academically.  I think it could fit with the new B-level (non-computational background skills).

**Comment by bast** [comment]
Yes - almost everybody needs to do this and it is practically never taught. In particular scripted figures which are easier to redo/modify.
